#index:
#    path: /
#    controller: App\Controller\DefaultController::index
dashboardFunder:
  path: /dashboardFunder
  methods: [GET]
  defaults: { _controller: 'App\Controller\LoginController::dashboardFunder' }